import React, { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const AVAILABLE_TABLES = [
  {
    key: 'users',
    label: 'Users',
    sql: `CREATE TABLE users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  username text UNIQUE NOT NULL,
  password text NOT NULL,
  role text NOT NULL
);`
  },
  {
    key: 'tasks',
    label: 'Tasks',
    sql: `CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  description text,
  status text,
  assigned_to text,
  inserted_at timestamptz DEFAULT now()
);`
  },
  {
    key: 'reports',
    label: 'Reports',
    sql: `CREATE TABLE reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint REFERENCES tasks(id),
  submitted_by text,
  details text,
  inserted_at timestamptz DEFAULT now()
);`
  }
];

export default function SupabaseSetup() {
  const [projectUrl, setProjectUrl] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [selected, setSelected] = useState({});
  const [sql, setSql] = useState('');

  useEffect(() => {
    const url = localStorage.getItem('supabaseUrl') || '';
    const key = localStorage.getItem('supabaseAnonKey') || '';
    setProjectUrl(url);
    setApiKey(key);
  }, []);

  const handleSave = () => {
    localStorage.setItem('supabaseUrl', projectUrl.trim());
    localStorage.setItem('supabaseAnonKey', apiKey.trim());
  };

  const handleGenerate = () => {
    const parts = AVAILABLE_TABLES.filter(t => selected[t.key]).map(t => t.sql);
    setSql(parts.join('\n\n'));
  };

  const toggle = (key) => {
    setSelected(prev => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <Card className="glass-effect border-sky-500/30 max-w-xl mx-auto">
      <CardHeader>
        <CardTitle>Supabase Configuration</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="projectUrl">Project URL</Label>
          <Input id="projectUrl" value={projectUrl} onChange={e => setProjectUrl(e.target.value)} placeholder="https://xyz.supabase.co" className="glass-effect" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="apiKey">API Key</Label>
          <Input id="apiKey" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="public anon key" className="glass-effect" />
        </div>
        <Button onClick={handleSave}>Save</Button>
        <div className="pt-4">
          <p className="font-semibold mb-2">Select tables to create:</p>
          {AVAILABLE_TABLES.map(t => (
            <label key={t.key} className="flex items-center gap-2">
              <input type="checkbox" checked={!!selected[t.key]} onChange={() => toggle(t.key)} />
              {t.label}
            </label>
          ))}
        </div>
        <Button className="mt-2" onClick={handleGenerate}>Generate SQL</Button>
        {sql && (
          <textarea readOnly className="w-full h-40 p-2 mt-4 bg-gray-800 text-white rounded" value={sql} />
        )}
      </CardContent>
    </Card>
  );
}
