import React, { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { getSupabaseClient, setSupabaseConfig } from '@/lib/customSupabaseClient';

const AVAILABLE_TABLES = [
  {
    key: 'users',
    label: 'Users',
    sql: `CREATE TABLE users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  username text UNIQUE NOT NULL,
  password text NOT NULL,
  role text NOT NULL
);`
  },
  {
    key: 'tasks',
    label: 'Tasks',
    sql: `CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  description text,
  status text,
  assigned_to text,
  inserted_at timestamptz DEFAULT now()
);`
  },
  {
    key: 'reports',
    label: 'Reports',
    sql: `CREATE TABLE reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint REFERENCES tasks(id),
  submitted_by text,
  details text,
  inserted_at timestamptz DEFAULT now()
);`
  }
];

export default function SupabaseSetup() {
  const [projectUrl, setProjectUrl] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [selected, setSelected] = useState({});
  const [sql, setSql] = useState('');
  const [copied, setCopied] = useState(false);

  const [fields, setFields] = useState([]);
  const [fieldSel, setFieldSel] = useState({});
  const [newField, setNewField] = useState('');

  useEffect(() => {
    const url = localStorage.getItem('supabaseUrl') || '';
    const key = localStorage.getItem('supabaseAnonKey') || '';
    setProjectUrl(url);
    setApiKey(key);

    try {
      const ignore = ['supabaseUrl', 'supabaseAnonKey'];
      const fieldSet = new Set();

      for (let i = 0; i < localStorage.length; i++) {
        const k = localStorage.key(i);
        if (!k || ignore.includes(k)) continue;
        const val = localStorage.getItem(k);
        try {
          const parsed = JSON.parse(val);
          const items = Array.isArray(parsed) ? parsed : [parsed];
          items.forEach(item => {
            if (item && typeof item === 'object') {
              Object.keys(item).forEach(f => fieldSet.add(f));
            }
          });
        } catch {
          /* ignore non JSON values */
        }
      }

      setFields(Array.from(fieldSet));
    } catch (e) {
      console.error('Failed to parse local data', e);
    }
  }, []);

  const handleSave = () => {
    setSupabaseConfig(projectUrl.trim(), apiKey.trim());
  };

  const handleGenerate = () => {
    const tableParts = AVAILABLE_TABLES.filter(t => selected[t.key]).map(t => t.sql);
    const selectedFields = fields.filter(f => fieldSel[f]);
    if (selectedFields.length) {
      const cols = selectedFields.map(f => `  ${f} text`).join(',\n');
      tableParts.push(`CREATE TABLE custom_table (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n${cols}\n);`);
    }
    setSql(tableParts.join('\n\n'));
  };

  const handleCopy = async () => {
    if (!sql) return;
    try {
      await navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Copy failed', e);
    }
  };

  const toggle = (key) => {
    setSelected(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const toggleField = (key) => {
    setFieldSel(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const handleAddField = () => {
    if (!newField.trim()) return;
    if (!fields.includes(newField.trim())) {
      setFields(prev => [...prev, newField.trim()]);
    }
    setFieldSel(prev => ({ ...prev, [newField.trim()]: true }));
    setNewField('');
  };

  const handleUpload = async () => {
    const supabase = getSupabaseClient();
    if (!supabase) {
      alert('Supabase not configured');
      return;
    }

    const data = JSON.parse(localStorage.getItem('tasks')) || [];
    const selectedFields = fields.filter(f => fieldSel[f]);
    const rows = data.map(item => {
      const obj = {};
      selectedFields.forEach(f => {
        obj[f] = item[f] ?? null;
      });
      return obj;
    });
    if (rows.length) {
      const { error } = await supabase.from('custom_table').insert(rows);
      if (error) alert(error.message); else alert('Data uploaded');
    }
  };

  return (
    <Card className="glass-effect border-sky-500/30 max-w-xl mx-auto">
      <CardHeader>
        <CardTitle>ربط بحساب Supabase</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <Tabs defaultValue="config">
          <TabsList className="mb-4">
            <TabsTrigger value="config">بيانات الربط</TabsTrigger>
            <TabsTrigger value="fields">المدخلات</TabsTrigger>
          </TabsList>

          <TabsContent value="config" className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="projectUrl">رابط المشروع</Label>
              <Input id="projectUrl" value={projectUrl} onChange={e => setProjectUrl(e.target.value)} placeholder="https://xyz.supabase.co" className="glass-effect" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="apiKey">مفتاح API</Label>
              <Input id="apiKey" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="public anon key" className="glass-effect" />
            </div>
            <Button onClick={handleSave}>حفظ</Button>
            <div className="pt-4">
              <p className="font-semibold mb-2">اختر الجداول المراد إنشاؤها:</p>
              {AVAILABLE_TABLES.map(t => (
                <label key={t.key} className="flex items-center gap-2">
                  <input type="checkbox" checked={!!selected[t.key]} onChange={() => toggle(t.key)} />
                  {t.label}
                </label>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="fields" className="space-y-4">
            <div className="flex gap-2">
              <Input value={newField} onChange={e => setNewField(e.target.value)} placeholder="اسم الحقل" className="glass-effect" />
              <Button onClick={handleAddField}>اضافة</Button>
            </div>
            <div className="space-y-2 max-h-60 overflow-y-auto">
              {fields.map(f => (
                <label key={f} className="flex items-center gap-2">
                  <input type="checkbox" checked={!!fieldSel[f]} onChange={() => toggleField(f)} />
                  {f}
                </label>
              ))}
            </div>
            <Button onClick={handleUpload}>رفع البيانات الحالية</Button>
          </TabsContent>

        </Tabs>

        <Button className="mt-2" onClick={handleGenerate}>توليد كود SQL</Button>
        {sql && (
          <>
            <textarea readOnly className="w-full h-40 p-2 mt-4 bg-gray-800 text-white rounded" value={sql} />
            <Button variant="outline" className="mt-2" onClick={handleCopy}">
              {copied ? 'تم النسخ' : 'نسخ الكود'}
            </Button>
          </>
        )}
      </CardContent>
    </Card>
  );
}
